[[libspatialite]]
arch = "aarch64"
git-tree-sha1 = "379857dc4fb6a11246fd68f48552b6c2082b294f"
os = "macos"

    [[libspatialite.download]]
    sha256 = "8ffb53003eb2ec3543f230b14e4fa45171383cdda732d46dd45057aa9dbc0366"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.aarch64-apple-darwin.tar.gz"
[[libspatialite]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79ddc681d7e697663cb6500b6a2865a9300178f3"
libc = "glibc"
os = "linux"

    [[libspatialite.download]]
    sha256 = "6d3de460860969eeb204f372aa8ddce18b53f7e3c39b4af49aa53985954eafc6"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[libspatialite]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79ddc681d7e697663cb6500b6a2865a9300178f3"
libc = "glibc"
os = "linux"

    [[libspatialite.download]]
    sha256 = "6d3de460860969eeb204f372aa8ddce18b53f7e3c39b4af49aa53985954eafc6"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libspatialite]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c4c209762abe49176a05203a4a3b194602b39319"
libc = "musl"
os = "linux"

    [[libspatialite.download]]
    sha256 = "a2c8c7c7670215fbfc03f2fda7fe50c04499f73bdeefa9dcd5e87d0eaea3505d"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[libspatialite]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4c209762abe49176a05203a4a3b194602b39319"
libc = "musl"
os = "linux"

    [[libspatialite.download]]
    sha256 = "a2c8c7c7670215fbfc03f2fda7fe50c04499f73bdeefa9dcd5e87d0eaea3505d"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[libspatialite]]
arch = "aarch64"
git-tree-sha1 = "6799f703b72685fd746233a91956e6922cf03443"
os = "freebsd"

    [[libspatialite.download]]
    sha256 = "1a6a02019311bc0db7ff2478cee144488cbc1834e375de57d1b7fb4209fb10a7"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.aarch64-unknown-freebsd.tar.gz"
[[libspatialite]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "965e7e5d9ac7f6861d064801933184f97647f422"
libc = "glibc"
os = "linux"

    [[libspatialite.download]]
    sha256 = "24ea3c110e04a48c3433a17fce530ec0e2252dd0b4edeaeea9d3568da359333e"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libspatialite]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "965e7e5d9ac7f6861d064801933184f97647f422"
libc = "glibc"
os = "linux"

    [[libspatialite.download]]
    sha256 = "24ea3c110e04a48c3433a17fce530ec0e2252dd0b4edeaeea9d3568da359333e"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libspatialite]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c37d214dea0368fe6a3e74a374315be538a923dd"
libc = "musl"
os = "linux"

    [[libspatialite.download]]
    sha256 = "087432d5d3f8a0ffce0103b2d53242781e85a15b0ed2b981b47e906885f72524"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libspatialite]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c37d214dea0368fe6a3e74a374315be538a923dd"
libc = "musl"
os = "linux"

    [[libspatialite.download]]
    sha256 = "087432d5d3f8a0ffce0103b2d53242781e85a15b0ed2b981b47e906885f72524"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libspatialite]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0189396281ef01b35c00ffadbb4e3d35871073c1"
libc = "glibc"
os = "linux"

    [[libspatialite.download]]
    sha256 = "d23e089abb7393d787571ba26cb8a2a9ac3808c29f6430320075668828a16d41"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libspatialite]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0189396281ef01b35c00ffadbb4e3d35871073c1"
libc = "glibc"
os = "linux"

    [[libspatialite.download]]
    sha256 = "d23e089abb7393d787571ba26cb8a2a9ac3808c29f6430320075668828a16d41"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libspatialite]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4eb8b04976ed306a85e5cde8c07ed4f9179a1916"
libc = "musl"
os = "linux"

    [[libspatialite.download]]
    sha256 = "5e7ed5aa26ff0d7062a5a0054b85d20df677aa5bfac4a33ba30d40678710ba0b"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libspatialite]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4eb8b04976ed306a85e5cde8c07ed4f9179a1916"
libc = "musl"
os = "linux"

    [[libspatialite.download]]
    sha256 = "5e7ed5aa26ff0d7062a5a0054b85d20df677aa5bfac4a33ba30d40678710ba0b"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libspatialite]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b7603f9d9d9bd4957a4db445bc52ed5db00013e"
libc = "glibc"
os = "linux"

    [[libspatialite.download]]
    sha256 = "fecb80a734ca593e5ec92d2da0090bbd698d868f66c39fb3cdfcdf39d24eef38"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.i686-linux-gnu-cxx03.tar.gz"
[[libspatialite]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b7603f9d9d9bd4957a4db445bc52ed5db00013e"
libc = "glibc"
os = "linux"

    [[libspatialite.download]]
    sha256 = "fecb80a734ca593e5ec92d2da0090bbd698d868f66c39fb3cdfcdf39d24eef38"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.i686-linux-gnu-cxx11.tar.gz"
[[libspatialite]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f97a13b7e0a40316d26910146c26156a4e2606bf"
libc = "musl"
os = "linux"

    [[libspatialite.download]]
    sha256 = "41f51bb149d124b91f81c6132dd73555e35713025b4de8adbc9f43ce243b6ce2"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.i686-linux-musl-cxx03.tar.gz"
[[libspatialite]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f97a13b7e0a40316d26910146c26156a4e2606bf"
libc = "musl"
os = "linux"

    [[libspatialite.download]]
    sha256 = "41f51bb149d124b91f81c6132dd73555e35713025b4de8adbc9f43ce243b6ce2"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.i686-linux-musl-cxx11.tar.gz"
[[libspatialite]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e69838d05ec6718024d923d4d9bd86dbaee6efd0"
os = "windows"

    [[libspatialite.download]]
    sha256 = "12f7a21181ae25ea5798b27b39dcc66ef5b750ed27ea8fb789d1a05967193078"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[libspatialite]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f0516c9e4273245f041ef25a6849da57b38012f"
os = "windows"

    [[libspatialite.download]]
    sha256 = "63adf7e1a3dc6eccceb87ab71d4a25445c8034c901c2ed0d471c97d9fa192979"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[libspatialite]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9cb9d4af93d40efeb04bc5d072993027e14bcde4"
libc = "glibc"
os = "linux"

    [[libspatialite.download]]
    sha256 = "67e5ad0d8ffa39320b6d97cbf4cdc78aadbff1b9d1dfdd07d7d800852c0fc2fe"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libspatialite]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9cb9d4af93d40efeb04bc5d072993027e14bcde4"
libc = "glibc"
os = "linux"

    [[libspatialite.download]]
    sha256 = "67e5ad0d8ffa39320b6d97cbf4cdc78aadbff1b9d1dfdd07d7d800852c0fc2fe"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libspatialite]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "10058e93b51c7a4b1bb5ebd30edafc2f7fc4b555"
libc = "glibc"
os = "linux"

    [[libspatialite.download]]
    sha256 = "665685eaf44f646c650f9052ffff7e21e3bd0e323096dcb0616425b54e9a1270"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.riscv64-linux-gnu-cxx03.tar.gz"
[[libspatialite]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10058e93b51c7a4b1bb5ebd30edafc2f7fc4b555"
libc = "glibc"
os = "linux"

    [[libspatialite.download]]
    sha256 = "665685eaf44f646c650f9052ffff7e21e3bd0e323096dcb0616425b54e9a1270"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.riscv64-linux-gnu-cxx11.tar.gz"
[[libspatialite]]
arch = "x86_64"
git-tree-sha1 = "6ac7809f98c7cdbbb06004c6238ce71feebc2d79"
os = "macos"

    [[libspatialite.download]]
    sha256 = "53e56408ee9051d31ee428ae8016f2afa9c15676a1a2e0e789ec209c38d510fe"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.x86_64-apple-darwin.tar.gz"
[[libspatialite]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6482db448450be6720e368fe646b437c760026ff"
libc = "glibc"
os = "linux"

    [[libspatialite.download]]
    sha256 = "0dfa7d0724ac0221844285888036cbcb2db5a9d922a74c20cfb3286e655d770e"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[libspatialite]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6482db448450be6720e368fe646b437c760026ff"
libc = "glibc"
os = "linux"

    [[libspatialite.download]]
    sha256 = "0dfa7d0724ac0221844285888036cbcb2db5a9d922a74c20cfb3286e655d770e"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libspatialite]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ecf8ddf281879f5e6cb4f75f2dcbc26486b0d3ce"
libc = "musl"
os = "linux"

    [[libspatialite.download]]
    sha256 = "401d66b2f0c5b75bf1158a1a01409446c1dc333e634b7f4acf8583f3e41ade95"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[libspatialite]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ecf8ddf281879f5e6cb4f75f2dcbc26486b0d3ce"
libc = "musl"
os = "linux"

    [[libspatialite.download]]
    sha256 = "401d66b2f0c5b75bf1158a1a01409446c1dc333e634b7f4acf8583f3e41ade95"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[libspatialite]]
arch = "x86_64"
git-tree-sha1 = "de1d8728b0daacc664b4f07552afe388b018a7e1"
os = "freebsd"

    [[libspatialite.download]]
    sha256 = "a10d1b35cedda9f0ad66679b1a44eeb70dbfd38f32d067ffd08656249502bc13"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.x86_64-unknown-freebsd.tar.gz"
[[libspatialite]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "171baecc02bf873966374a938a017b593c6b9ef9"
os = "windows"

    [[libspatialite.download]]
    sha256 = "373194094879474727687222176b84d51849e097fde6c1413992f56f10d907a7"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[libspatialite]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e55ca396dd1c9a22c9156d1dccfee5820bf4026"
os = "windows"

    [[libspatialite.download]]
    sha256 = "1ffaae8d055eb8b988fe6ad43bd5e715b262ff5c8d6102846190788d80e2c935"
    url = "https://github.com/JuliaBinaryWrappers/libspatialite_jll.jl/releases/download/libspatialite-v5.1.0+0/libspatialite.v5.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
